stages:
    - format
    - test
    - release

black_formatting:
  image: python:3.7-slim-stretch
  stage: format
  
  before_script:
    - pip install black

  script:
    # use black on the code
    # '--check' returns error code 1, if something needs formatting
    - black . --check --exclude '\.venv/|\.local/|\.cache/|\.git/|migrations/'

  allow_failure: false
  
code_test:
  stage: test
  image: themattrix/tox
  services:
    - postgres:10-alpine
  variables:
    POSTGRES_DB: ci
  script:
    - tox

pypi_release:
  stage: release
  image: python:3.7-slim-stretch
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags
  when: manual
