# Generated by Django 2.1 on 2020-10-03 17:10

from django.db import migrations


def add_test_record(apps, schema_editor):
    """Adds a test record so we have something to test against."""
    demo_migration_model = apps.get_model('encrypted_fields_test', 'DemoMigrationModel')
    # Add a row if none exist - to test our data migrations on.
    demo_migration_model.objects.get_or_create(data="bye", info="foo")


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_fields_test', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_test_record, reverse_code=migrations.RunPython.noop)
    ]
