# Generated by Django 2.1 on 2020-10-03 17:05

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_fields_test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoMigrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10, default='hi')),
                ('info', models.CharField(max_length=10, default='')),
                ('encrypted_data', encrypted_fields.fields.EncryptedCharField(default='hi', max_length=10)),
                ('encrypted_info', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('searchable_encrypted_info', encrypted_fields.fields.SearchField(default='', db_index=True, encrypted_field_name='encrypted_info', hash_key='abc', max_length=66, null=True)),
                ('_encrypted_data', encrypted_fields.fields.EncryptedCharField(max_length=10)),
                ('searchable_encrypted_data', encrypted_fields.fields.SearchField(default='hi', db_index=True, encrypted_field_name='_encrypted_data', hash_key='abcd', max_length=66, null=True)),
            ],
        ),
    ]
