# Generated by Django 2.1 on 2020-10-08 10:05

import datetime
from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_fields_test', '0002_demomigrationmodel_add_test_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomigrationmodel',
            name='_default_char',
            field=encrypted_fields.fields.EncryptedCharField(default='foo default', max_length=20),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='_default_date',
            field=encrypted_fields.fields.EncryptedDateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='_default_number',
            field=encrypted_fields.fields.EncryptedPositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='searchable_default_char',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_default_char', hash_key='123abc', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='searchable_default_date',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_default_date', hash_key='123abc', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='default_encrypted_char',
            field=encrypted_fields.fields.EncryptedCharField(default='encrypted hi', max_length=20),
        ),
        migrations.AddField(
            model_name='demomigrationmodel',
            name='searchable_default_number',
            field=encrypted_fields.fields.SearchField(blank=True, db_index=True, encrypted_field_name='_default_number', hash_key='123abc', max_length=66, null=True),
        ),
    ]
