# Generated by Django 2.1 on 2020-10-03 17:10

from django.db import migrations


def migrate_data_and_info(apps, schema_editor):
    """Demonstrates migrating from a model.CharField -> EncryptedCharField and migrating
     a (different) model.CharField -> SearchField (with associated EncryptedField).

     Note: we have not *altered* any fields. We have added new fields."""
    demo_migration_model = apps.get_model('encrypted_fields_test', 'DemoMigrationModel')
    # The actual data migration:
    for obj in demo_migration_model.objects.all():
        # Assigning obj.data to the new EncryptedField ensures the data is encrypted.
        obj.encrypted_data = obj.data
        # Only migrate data to the SearchField, the SearchField will populate the
        # associated EncryptedField.
        obj.searchable_encrypted_info = obj.info
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_fields_test', '0003_demomigrationmodel_add_more_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_data_and_info, reverse_code=migrations.RunPython.noop)
    ]
