# Generated by Django 2.1 on 2020-10-03 17:10

from django.db import migrations


def rotate_keys(apps, schema_editor):
    """Demonstrates migrating all rows to use the newest encryption key.

    This assumes you have prepended 'settings.FIELD_ENCRYPTION_KEYS' with a new key."""
    demo_migration_model = apps.get_model('encrypted_fields_test', 'DemoMigrationModel')
    for obj in demo_migration_model.objects.all():
        # fetching and saving the object 'gets' and then 'sets' each attribute,
        # decrypting with the old key and encrypting with the new key.
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('encrypted_fields_test', '0005_data_migration_example_2'),
    ]

    operations = [
        migrations.RunPython(rotate_keys, reverse_code=migrations.RunPython.noop),
    ]
